para_xgboost = {'booster': 'gbtree',
      'objective': 'binary:logistic',
      #'objective': 'multi:softmax',
      #'num_class': 6,
      'eval_metric': 'auc',
      #'eval_metric': 'mlogloss',
      'max_depth': 10,
      'lambda': 0.4,
      'subsample': 0.75,
      'colsample_bytree': 0.8,
      'min_child_weight': 1,
      'eta': 0.025,
      'seed': 0,
      'nthread': 8,
      'silent':1,
      'gamma': 0.15,
      'learning_rate': 0.1,
      'verbose_eval':True
}
xgboost_loop_num = 500
