# .bashrc
alias rm='rm -i'
alias cp='cp -i'
#alias mv='mv -i'
alias vi=vim

if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
export davidyu=/home/davidyu
# added by Anaconda3 2018.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/davidyu/software/Anaconda/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/davidyu/software/Anaconda/etc/profile.d/conda.sh" ]; then
        . "/home/davidyu/software/Anaconda/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/davidyu/software/Anaconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
export HIVE_HOME=/home/davidyu/software/apache-hive-3.1.1-bin
PATH=$PATH:/home/davidyu/software/apache-hive-3.1.1-bin/bin
export SPARK_HOME=/home/davidyu/software/spark-2.4.0-bin-hadoop2.7
export PATH=$SPARK_HOME/bin:$SPARK_HOME/sbin:$PATH
export PATH=$PATH:/home/davidyu/software/phantomjs-2.1.1-linux-x86_64/bin
export PATH=$PATH:/usr/local/bin/geckodriver
export PATH=$PATH:/home/davidyu/software/chrome
export LANG="zh_CN.UTF-8"
LANGUAGE=zh_CN.UTF-8
# system path
export LD_LIBRARY_PATH="/usr/lib:$LD_LIBRARY_PATH"
#################################################
export SCALA_HOME=/usr/local/scala/scala-2.11.12
export PATH=$PATH:$SCALA_HOME/bin
export PATH=$PATH:$MAVEN_HOME/bin
###### davidyu path 
export main_dir="/home/davidyu/stock/"
export stock_script=$main_dir"scripts/davidyu_stock/scripts/"
export THE_functions=$stock_script"functions/"
export stock_data=$main_dir"data"
export data_tmp_dir=$stock_data"/tmp"
export log_dir=$main_dir"log"
export result_data=$main_dir"data_result"
export MAVEN_HOME=/home/davidyu/software/apache-maven-3.6.0
alias removefirstline=/home/davidyu/stock/scripts/davidyu_stock/scripts/system_command/rm_1lines.sh
### pyspark driver
export PYSPARK_DRIVER_PYTHON=ipython 
#export PYSPARK_DRIVER_PYTHON_OPTS=”notebook”
export python_libs="/home/davidyu/software/Anaconda/lib/python3.7/site-packages"
### the dir to save log
## shell function dir
export shell_function_dir="/home/davidyu/stock/scripts/davidyu_stock/scripts/shell_function/"


