feature_columns = ["rsi_6", "rsi_12", "rsi_24", "kdjk", "kdjd", "kdjj", "macdh", "boll_ub", "boll_lb", "boll_ratio",
        "mv_avg_3_5","mv_avg_3_8","mv_avg_3_13","mv_avg_5_8",
        "close_mvavg3",
        "close_mvavg5",
        "close_mvavg8",
        "close_mvavg13",
        "close_mvavg21",
        "high_mvavg3",
        "high_mvavg5",
        "high_mvavg8",
        "high_mvavg13",
        "high_mvavg21",
        "low_mvavg3",
        "low_mvavg5",
        "low_mvavg8",
        "low_mvavg13",
        "low_mvavg21",
        "open_mvavg5",
        "open_mvavg8",
        "open_mvavg13",
        "open_mvavg21"]

